name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        install_components: 'beta'

    - name: Configure Docker
      run: gcloud auth configure-docker asia-southeast2-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/capstone_docker_c241-ps342:latest .

    - name: Push Docker image
      run: |
        docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/capstone_docker_c241-ps342:latest

    - name: Deploy to Cloud Run
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > keyfile.json
        gcloud run deploy c241-ps342-cc \
          --image asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/capstone_docker_c241-ps342:latest \
          --platform managed \
          --region asia-southeast2 \
          --allow-unauthenticated \
          --set-env-vars GOOGLE_APPLICATION_CREDENTIALS=/workspace/keyfile.json
